### ISSUE TITLE
Include relaxation in the design process

### ISSUE THREAD

**Issue by amin-sagar** [Kuhlman-Lab/evopro#15]
Hello.
Thanks again for this awesome work.
I am wondering if it's possible to include a relaxation step in the design process.
My thought is that since MPNN is dependent on the backbone coordinates, the performance might improve if the backbone is allowed to relax in each generation. 
This also seems to be indicated in https://www.nature.com/articles/s41467-023-38328-5
![image](https://github.com/Kuhlman-Lab/evopro/assets/118898409/faf23a25-57e2-47da-83cd-219281cb85df)
Could you give me some pointers on where I should start to include a relaxation step using amber or openmm in the design protocol?

**Comment by amritan1707** [comment]
Hi,

Thanks for your interest in EvoPro!
It should be relatively straightforward to include a relaxation step in the process - most likely you will want to do this before the step where the pool is refilled with ProteinMPNN.

The main obstacle is that you will need to have a python version of whatever relaxation protocol you would like to use and it's module and dependencies should be compatible with our existing conda environment. Once you have added the required modules into the conda env, you can call the relax protocol on the PDBs right before refill step.

The best place to start is probably above line 84 in evopro/run/run_geneticalg_gpus.py). At this point there exists a pool of objects representing the optimizing population. Each object has a sequence, some PDBs associated with it, and scores. You can replace here the PDBs with relaxed PDBs before calling pMPNN.

Please do not hesitate to respond to this issue with further questions.
