### ISSUE TITLE
Can vary_length be used with the stable branch?

### ISSUE THREAD

**Issue by amin-sagar** [Kuhlman-Lab/evopro#22]
Hello.
I would like to use the vary_length option to refine my binder.
It seems that the argument is not accepted by the stable branch but works with the dev branch.
I can change the script to accept it but I wanted to know if there is something wrong with using this with the stable branch and that's why this option has not been enabled in the stable branch.
I would really appreciate your suggestions.
Best,
Amin.

**Comment by amritan1707** [comment]
Hi, we have seen some rare, strange errors (probably some edge cases) when using the vary_length option - so you can use it, but the program may crash rarely! This is why we have not enabled this option in the stable branch.
