### ISSUE TITLE
Format of custom-msa

### ISSUE THREAD

**Issue by amin-sagar** [Kuhlman-Lab/evopro#7]
Hello.
Thanks for making this awesome project available.
I can run the example scripts if I remove the 
--msa_mode 
--custom_msa_path 
part.
But, this results in the receptor not folding properly.
I would like to use the protocol described in the paper, give custom msa for the receptor.
I tried generating an msa for the receptor alone and supply it by giving path to the folder containing the a3m file, but I get an error 
```
Traceback (most recent call last):
  File "/home/amin/anaconda3/envs/af2_mpnn2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/amin/anaconda3/envs/af2_mpnn2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/amin/softwares/EVOPRO/evopro/evopro/utils/distributor.py", line 128, in _worker_loop
    result = f(val)
  File "/home/amin/softwares/EVOPRO/alphafold/run/run_af2.py", line 243, in af2
    raw_inputs_from_sequence = getRawInputs(
  File "/home/amin/softwares/EVOPRO/alphafold/run/features.py", line 68, in getRawInputs
    custom_msas.update(getCustomMSADict(custom_msa_path))
  File "/home/amin/softwares/EVOPRO/alphafold/run/features.py", line 483, in getCustomMSADict
    custom_msa_dict[seq].append(line)
KeyError: None
```
My MSA file looks like this
```
#214    1
>101
AFTVTVPKDLYVVEYGSNMTIECKFPVEKQLDLAALIVYWEMEDKNIIQFVHGEEDLKVQHSSYRQRARLLKDQLSLGNAALQITDVKLQDAGVYRCMISYGGADYKRITVKVNAPYNKINQRILVVDPVTSEHELTCQAEGYPKAEVIWTSSDHQVLSGKTTTTNSKREEKLFNVTSTLRINTTTNEIFYCTFRRLDPEENHTAELVIPELPL
>UniRef100_UPI001B349335        187     0.771   9.977E-50       0       213     214     39      251     311
AFTITVPKDQYVVEYGSNVTIECKFPVEKPLDLNSLVVYWEKGGKQIIQFVHGKEDPKVQHGSYRQRARLLEDRFYEGIAALQITDVKLQDAGIYCCLISYGGADYKRITLKVNAPYHKINQRISV-DPVTSEHELTCQAEGYPEAEVIWTNRDHQILHGKTILTSSNREEQFFNVTSTLRVNATANEIYYCTFQRPGPEENNTAELIIPEPPV
>UniRef100_A4GW17       185     0.962   4.804E-49       0       213     214     17      230     290
AFTVTVPKDLYVVEYGSNMTIECKFPVEKQLDLTSLIVYWEMEDKNIIQFVHGEEDLKVQHSNYRQRAQLLKDQLSLGNAALRITDVKLQDAGVYRCMISYGGADYKRITVKVNAPYNKINQRILVVDPVTSEHELTCQAEGYPKAEVIWTSSDHQVLSGKTTTTNSKREEKLLNVTSTLRINTTANEIFYCIFRRLDPEENHTAELVIPELPL
>UniRef100_A0A8B7U6V9   184     0.822   1.689E-48       0       213     214     17      229     268
```
Could you please guide me about the format of the msa file to be supplied. Or if you can share the msa that you used with the example given in the repository, I can try to understand the format.
Best,
Amin.

**Comment by nzrandol** [comment]
Hello Amin, thanks for your interest! I've just made pushed an update to our [AF2 installation](https://github.com/Kuhlman-Lab/alphafold) that should address this issue. Essentially, your custom MSA is formatted correctly, but the parsing expected the first line to start with `>`. (So, removing that first line should have also solved the issue). Please update your repository and let me know if this fixes your issue!

**Comment by amin-sagar** [comment]
Thanks @nzrandol 
It works perfectly after the update.
Amin.
